### ISSUE TITLE
Using hostBinding fn with class returns undefined

### ISSUE THREAD

**Issue by tutkli** [nartc/ngxtension-platform#130]
I was trying the hostBinding function to bind some classes to a component but it returns undefined.

Example:
```ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { hostBinding } from 'ngxtension/host-binding';

@Component({
  selector: 'mtx-toolbar',
  standalone: true,
  template: ` <ng-content/>  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ToolbarComponent {
  hostClass = hostBinding('class', signal('bg-blue-500'));
}
```

![image](https://github.com/nartc/ngxtension-platform/assets/49206247/8ea3310e-8257-447b-998d-361f59e1fee3)

**Comment by tutkli** [comment]
I got it working using: 
```ts
hostBinding('attr.class', signal('bg-blue-500'))
```

I was trying to replicate this:
```ts
@HostBinding('class') hostClass = 'bg-blue-500;
```

**Comment by LcsGa** [comment]
Indeed, I didn't remember that we could simply set the class like this 😅.
Only had the `class.something` syntaxe in mind! I'll fix this asap!

**Comment by nartc** [comment]
Close with #131
