### ISSUE TITLE
[RFC] Inject route params as signal

### ISSUE THREAD

**Issue by wanoo21** [nartc/ngxtension-platform#137]
We recently talked about the `injectParamsMap` function on 𝕏, It may be a good idea to add them here as well.

Here's the code I'm talking about:

```ts
export function injectParamsMap(injector?: Injector): Signal<ParamMap> {
  return assertInjector(injectParamsMap, injector, () => {
    const route = inject(ActivatedRoute);
    return toSignal(route.paramMap, {
      initialValue: route.snapshot.paramMap,
    });
  });
}
```

It can include three functions, `injectParamsMap`, `injectQueryParams`, and `injectRouteData`. 

Let me know what you think!

**Comment by nartc** [comment]
Let's just wait a bit more to see if we hear anything about Signal Input after v17 release

**Comment by wanoo21** [comment]
Okay, sure
