### ISSUE TITLE
You're using a dependency which uses ejs v3.1.9, Which is vulnerable to server-side template injection

### ISSUE THREAD

**Issue by endlacer** [nartc/ngxtension-platform#156]
![image](https://github.com/nartc/ngxtension-platform/assets/66420187/cf3e3dac-0e53-40d2-9a89-9942cef2f04f)

Is it necassary to use @nx/devkit ?

https://github.com/advisories/GHSA-j5pp-6f4w-r5r6

**Comment by nartc** [comment]
`ejs` is used by the `nx/devkit` for running generators which are only ran on the dev machine so the vulnerability is irrelevant to `ngxtension`
