### ISSUE TITLE
[Docs] computedFrom - fix example with provided injection context

### ISSUE THREAD

**Issue by gianmarcogiummarra** [nartc/ngxtension-platform#159]
Hello everyone,
reading the docs about the `computedFrom` function I realized that the example at [computedFrom - Use it outside of an injection context](https://ngxtension.netlify.app/utilities/signals/computed-from/#5-use-it-outside-of-an-injection-context) doesn't reflect the actual function's signature.

The function is now defined as:

```
export function computedFrom<Input extends readonly unknown[], Output = Input>(
	sources: readonly [...ObservableSignalInputTuple<Input>],
	operator?: OperatorFunction<Input, Output>,
	options?: ComputedFromOptions<Output>
): Signal<Output>;

```

And the doc shows the old usage passing the `injector` as the third argument, instead of passing the `options` object.

I believe a change in the doc could help reflecting the changes made through [PR 122](https://github.com/nartc/ngxtension-platform/pull/122), @dmorosinotto could you please confirm?

After your confirmation, I could be able to open a PR to adapt the docs in the next hours. 

Thank you!

**Comment by dmorosinotto** [comment]
Yes you are right @gianmarcogiummarra 
I missed to update the docs sample - Good catch 👍

**Comment by gianmarcogiummarra** [comment]
Thanks @dmorosinotto 😄 

I opened the [PR 160](https://github.com/nartc/ngxtension-platform/pull/160)
