### ISSUE TITLE
Feature Request: Add `withCommandState` RxJS Operator

### ISSUE THREAD

**Issue by nikosanif** [nartc/ngxtension-platform#180]
## Description

**Overview:**
I propose adding a new RxJS operator, `withCommandState`, to enhance the functionality of the existing library regarding RxJS interoperability. This operator aims to simplify state management in asynchronous operations (e.g. HTTP requests), providing a convenient way to handle loading, success, and error states.

**Motivation:**
Currently, managing state in asynchronous operations can be verbose. The proposed operator aims to streamline this process, making it more concise and readable.

## Proposed Implementation

**Operator Signature:**
```typescript
interface CommandState<T, E> {
  status: 'pending' | 'loading' | 'success' | 'error';
  error: E | null;
  data: T | null;
}

function withCommandState<T, E>(): Observable<CommandState<T, E>>;
```

**Usage Example:**
```typescript
import { withCommandState } from 'ngxtension/rxjs-interop';

const data$ = fetchData().pipe(
  withCommandState(),
  tap(state => console.log('Current State:', state))
);
```

#### Additional Considerations

- The name of the operator is just a suggestion, new ideas for the name are totally welcome.
- We can create either a specific secondary entry point for this operator or a generic for `rxjs-interop`. Again, it's under discussion.

Last but not least, I am happy to contribute to this ticket if you find it useful! Just drop the green light!

**Comment by rlmestre** [comment]
This seems related to #56

**Comment by eneajaho** [comment]
Let's follow this in #56 🙌
