### ISSUE TITLE
Question: Is there a way to create composite selectors in signalSlice?

### ISSUE THREAD

**Issue by robbaman** [nartc/ngxtension-platform#187]
When creating a selector in signalSlice it seems you must always use the main `state()` signal. While I may just not understand exactly how this works, but from my understanding this means that the signal is triggered on a pretty high level, which is especially painful when using nested trees or complicated logic in the selector.

For instance, I have some state that consists of a several nested trees of data. Using signalSlice's `selector` I've created a selector that combines data from several parts of the state to one viewmodel.

Now I would like to extend on this viewmodel with another selector that builds on the complex work that the initial selector does, but I don't really see a way how to do this.

Is there a way to have a selector reference another selector?

```typescript
selectors: (state) => ({
  playersWithAttendance: () => {
    // Doesn't this selector triggeron ALL changes ANYWHERE in the state, even when it's 
    // not related to either the players or the match property?
    // It would've been better if state.players() could be used right?
    const players = state().players;
    const match = state().match;

    return players.map(i => ({...i, attending: !!~match.attendingPlayerIds.indexOf(i.id)}))
  },
  attendingPlayersOnly: () => {
    // This doesn't work
    return playersWithAttendance().filter(i => i.attending);
  }
}),
```

**Comment by joshuamorony** [comment]
Composite selectors isn't actually something I had properly considered yet - I doubt we would be able to have the ability for custom selectors to reference other custom selectors, but I do like the pattern you have landed on anyway.

Ideally though you wouldn't have to create the computed selectors for the top level state manually - you have to here of course because the state the is passed in to the selectors function is just a signal of the state, whereas `effects` and `actionEffects` for example are passed the full state object. I don't actually recall if there is a specific reason why the full SignalSlice object is not passed into the selectors, but it might be that we can just pass in the full SignalSlice and then you could just do this:

```ts
selectors: (state) => {

  const attendingPlayerIds = computed(() => state.match().attendingPlayerIds);
  const playersWithAttendance = computed(() => {
      return state.players().map(i => ({...i, attending: !!~attendingPlayerIds().indexOf(i.id)}))
    });

  return {
    // Simply return the computed signals
    playersWithAttendance: playersWithAttendance,
    // Or create a new function that uses one of the computed signals
    attendingPlayersOnly: () => {
      // Now this does work!
      return playersWithAttendance().filter(i => i.attending);
    }
  };
},
```

If we are able to pass in the full SignalSlice object to selectors it should be a non-breaking change because it can still be accessed as a normal signal as well and the original code you posted should continue to work.

**Comment by robbaman** [comment]
My guess would be because it isn't available there yet. The `selectors` property is part of the initialization object provided to the `signalSlice` function whose result type is dynamically determined by the top level properties of the `selectors` property. If you'd be able to provide the signalSlice result type to the I would guess you'd get a cyclical reference of some kind.

But also, this would mean that to utilize multi level computed signals you'd have to make each intermediate step available through the state object's selector too. Notice how my example never actually exposes the computed `attendingPlayerIds` computed signal.

**Comment by joshuamorony** [comment]
I think it *should* work just by moving the 'slice' declaration above the selectors and passing in slice instead of readonlyState:

```ts
	const slice = readonlyState as SignalSlice<
		TSignalValue,
		TActionSources,
		TSelectors,
		TEffects
	>;

	for (const [key, selector] of Object.entries(selectors(slice))) {
		Object.defineProperty(readonlyState, key, {
			value: computed(selector),
		});
	}
```

If anyone wants to give it a go and add in a couple of tests for accessing the selectors feel free, otherwise I can investigate this more thoroughly a little later

**Comment by robbaman** [comment]
Haha, I was just looking into it and you're right.

I created a PR with the changes but have to admit that I'm not sure how to run the tests for the project 🤷🏻‍♂️

Using the changed version works for allowing the default selectors from the top level properties of the initial state. It doesn't help with the deeper computed signals, but I can use the pattern I originally discovered for this.

https://github.com/nartc/ngxtension-platform/pull/188
