### ISSUE TITLE
[Suggestion] Make signalSlice sources lazy load

### ISSUE THREAD

**Issue by keithotto** [nartc/ngxtension-platform#196]
I noticed in my service where I had created 4 signalSlice objects that they all eagerly fetch their data from their source immediately when the service is first created.

These slices are used in different pages of the website, and it's entirely possible one or more of them may never be called on if the user never visits those pages, so it seems wasteful to be loading that data in advance. 

Would it be possible to delay subscribing to the source observable until the first time a slice has been accessed?

**Comment by nartc** [comment]
Thanks for the suggestion @keithotto 

It'd be tricky to make `signalSlice` sources lazy-load; there might be cases where a configurable `eager` or `lazy` is desired. So, we probably need some time to think about the API for this one.

To work around this, you can start your sources with a subject/many subjects and then the subject when you want to start the sources.

```ts
// instead of
signalSlice({
  sources: [mySource$]
});

// maybe?
const trigger = new Subject();
signalSlice({
  sources: [trigger.pipe(switchMap(() => mySource$))]
})
```

I know it's verbose, but I can't think of anything else off the top of my head.

**Comment by joshuamorony** [comment]
If anyone has any comments I have a little prototype here: https://github.com/joshuamorony/ngxtension-platform/blob/feature/signal-slice-lazy-sources/libs/ngxtension/signal-slice/src/signal-slice.ts

Still need to do a bit of refactoring/testing but the general idea is adding `lazySources` to the config and only using `connect` for those sources  when the state object is accessed via using a `Proxy`.

I'll finish this up soon unless anyone has other ideas

**Comment by joshuamorony** [comment]
Opened a draft PR for this - all seems to work fine, but still facing one blocking issue (detailed in the PR)

**Comment by joshuamorony** [comment]
@keithotto v1.6.0 is out with this change included - I've left it undocumented for now, would you mind giving it a go to see if it works well for your use case and let me know?

**Comment by keithotto** [comment]
I will test it out tomorrow for sure! So it's just as you mentioned above to use `lazySources `instead of `sources`?

**Comment by nartc** [comment]
@keithotto yes

**Comment by keithotto** [comment]
Ok I gave 1.6.0 a quick test with lazySources. It's working well, but I found one case that doesn't seem to trigger the lazy loading. It looks like if you call on the top level signalSlice in your code / template it doesn't connect the lazy source. Admittedly your docs recommend binding to the selectors anyways but it might be something people do.

If I have this in my `AppService`:
```
public $tags = signalSlice({
    initialState: this._tagsInitialState,
    lazySources: [this._getTags()],
});
```

In the code for my component that uses this data I have:
`$tags = this._appService.$tags;`

Then in the component HTML I bind to that with:
```
<ul class="app-library-tags">
        @for (tag of $tags().data; track tag.id) {
        <li>
          <label
            ><input type="checkbox" id="tag-{{ tag.id }}" />
            {{ tag.name }}</label
          >
        </li>
        }
</ul>
```

In this configuration the lazySource will never get triggered. 

If I change the location of the ( ) brackets from `$tags().data` to `$tags.data()` when binding to the signalSlice it works fine:
```
<ul class="app-library-tags">
        @for (tag of $tags.data(); track tag.id) {
        <li>
          <label
            ><input type="checkbox" id="tag-{{ tag.id }}" />
            {{ tag.name }}</label
          >
        </li>
        }
</ul>
```

**Comment by joshuamorony** [comment]
Thanks for testing @keithotto - I did explicitly consider the signal value being accessed directly and intended for that to work as well. I'll look into this.

**Comment by joshuamorony** [comment]
I've fixed this here btw: https://github.com/joshuamorony/ngxtension-platform/tree/fix/signal-slice-lazy-sources

Just need to figure out why my Prettier setup is removing trailing commas... then I'll open a PR

**Comment by nartc** [comment]
1.6.1 has been released. If you can test it out @keithotto, that'd be great

**Comment by keithotto** [comment]
A quick test here confirms that accessing the root signal in the template is now working as well. All seems to be well, thanks guys!
