### ISSUE TITLE
[Bug] - signalSlice - selector does not work with effects

### ISSUE THREAD

**Issue by krivanek06** [nartc/ngxtension-platform#204]
Hello,

I am trying out signal-slice and I observed that when I use `selectors` with `effects` then some functionalities from the store are not accessible based on which one of them is the first. Here is an example. When I have the following:

```TS
@Injectable({
  providedIn: 'root',
})
export class TestStoreService {
  state = signalSlice({
    initialState: this.initialState,
    sources: [ /* */],
    selectors: (state) => ({
      getGroups: () => state.groups,
    }),
    effects: (state) => ({
      saveGroups: () => {
        console.log('Store save groups called');
      },
    }),
  });
}
```
then I am not able to call `this.testStoreService.state.saveGroups();`, however when I change the order of `effects` with `selectors` , such that `effects` is first, then I am not able to call any `selectors`.

Here is the reproduction of the problem: https://stackblitz.com/edit/stackblitz-starters-repewo

**Comment by joshuamorony** [comment]
Thanks for the issue -  `effects` are not intended to be callable, these are executed based on any signals the effect references changing, e.g:

```ts
    effects: (state) => ({
      saveGroups: () => {
        state.something();
      },
    }),
```

In this case `saveGroups` will run when `something` changes and also once initially - it can't be manually called. You probably want something like this:

```ts
    effects: (state) => ({
      saveGroups: () => {
        const groups = state.groups();
        // do something every time state.groups() changes
      },
    }),
```

However, we still should probably not be exposing the `EffectRef` on the type in the first place. The typing for `selectors` failing when they are defined after `effects` is definitely a problem though.

**Comment by krivanek06** [comment]
I see, thank you @joshuamorony for the explanation. I was initially thinking that I can manually call `saveGroups` . Maybe the docs should be updated or I just overlooked it.
Nonetheless thanks for the fast response, I am closing the issue.
