### ISSUE TITLE
Merge signals 

### ISSUE THREAD

**Issue by baffioso** [nartc/ngxtension-platform#221]
Looked through the docs of this wonderful library and couldn't find a  signal utility for merging two or more signal (like [RxJS merge](https://rxjs.dev/api/operators/merge)).

Have I overlooked an easy way to do this without an helper function or is this suitable as an ngxtension util?

**Comment by nartc** [comment]
similar to `merge()` from rxjs, I don't think there is one right now. But I'd like to hear about your use-case on a `merge()` for Signals.

**Comment by baffioso** [comment]
I have som geographical data which is both presented in a table and on a map. 

<img width="493" alt="image" src="https://github.com/nartc/ngxtension-platform/assets/7534153/efccee68-34c0-4b89-815e-54068467d0bd">

<img width="492" alt="image" src="https://github.com/nartc/ngxtension-platform/assets/7534153/d0e71a54-ea4e-406c-a49b-a0761ce10bb3">

When i click a feature on the map OR a row in the table i want to update a signal with the id of the selected map feature or table row. The selected id from the map feature and the table column are stored in two different signals. I want to create a signal which merges the "map-signal" and the "table-signal" emitting the latest id. 

Hope it make sense.

**Comment by nartc** [comment]
I see. It makes sense. Right now, I'd workaround it by

```ts
toSignal(
  merge(
    toObservable(fromMap), 
    toObservable(fromTable)
  )
)
```

But if we have something like `mergeFrom()` we can accept a mix of Observables and Signals too.

**Comment by baffioso** [comment]
Thanks for the workaround. `mergeFrom` sound like what i was looking for.

**Comment by baffioso** [comment]
Thank you!!
