### ISSUE TITLE
computedAsync must return T | undefined, but returns T

### ISSUE THREAD

**Issue by zip-fa** [nartc/ngxtension-platform#243]
Hi. computedAsync returns T for now, but must return T | undefined.
This simple code will throw error in template, because its initial value is undefined, but not `TestResponse`:

```ts
type TestResponse = {
  results: string[];
};

protected readonly test = computedAsync(() => this.httpClient.get<TestResponse>('/test'));
```

```html
@for (result in test().results) { // <--- error is thrown here
{{ result }}
}
```

**Comment by eneajaho** [comment]
Hi, thanks for opening the issue. 
@nartc I need help with the typings here 😄

I think I haven't seen this issue because I always provide that initialValue.

**Comment by JeanMeche** [comment]
@eneajaho Let me try my luck on this :)
