### ISSUE TITLE
deprecate extendedComputed util 

### ISSUE THREAD

**Issue by eneajaho** [nartc/ngxtension-platform#246]
https://ngxtension.netlify.app/utilities/signals/computed/

**Comment by Akxe** [comment]
Why? I do not see an alternative. Also, info in the deprecation notes about what the replacement is would be great.

**Comment by eneajaho** [comment]
Hello @Akxe 
Do you have any particular usecase for this util? 

This was included in computedAsync util, and that's the only place where we thought this would be necessary.

**Comment by Akxe** [comment]
I have a signal that needs to be updated only when one other one is true:

```
const visible = signal(false);
computedWithPrevious(previous => {
    if (!visible()) {
        return previous;
    }
    
    // ... actually compute the current state that depends on multiple other signals
});
```

**Comment by eneajaho** [comment]
I understand now. 

We have another utility in ngxtension `computedPrevious`

```ts
import { computedPrevious } from 'ngxtension/computed-previous';

const visible = signal(false);

const computedValueYouNeed = computed(() => {
  // ... actually compute the current state that depends on multiple other signals
});

const previousComputedValueYouNeed = computedPrevious(computedValueYouNeed);

const finalComputed = computed(() => {
    if (!visible()) {
        return previousComputedValueYouNeed();
    }
    return computedValueYouNeed();
});
```

I understand it's more lines of code, but this way we don't provide a function that has the same functionality as computed but with just a small difference in the name.


Does this solve your issue?

**Comment by Akxe** [comment]
I used this:

```javascript
const visible = signal(false);
let previous = [];
computedWithPrevious(previous => {
    if (!visible()) {
        return previous;
    }
    
    const result = // ... actually computes the current state that depends on multiple other signals
    
    return previous = result;
});
```

**Comment by rlmestre** [comment]
I opened up a discussion in the Angular repo about this. It's not likely to happen, but if you have any compelling use cases, please share them!

https://github.com/angular/angular/issues/54339

**Comment by Akxe** [comment]
I appreciate your activity, but they are right. I did find a way around it. I think that `previous` signal value should not be part of angular as it may lead developers to bad practices. For me, I only tend to use previous values in computations when I need to solve performance issues, like the one above.

**Comment by endlacer** [comment]
It should be explained in the deprecation comment though..
