### ISSUE TITLE
ver: 2.0.0 computedAsync types not working any more

### ISSUE THREAD

**Issue by sysmat** [nartc/ngxtension-platform#266]
- Are any migration docs from ver 1.12.0 to ver 2.0.0
- In VSC there is no error but when using `ng build` I get compile error
- use case which work in ver 1.12.0:

```typescript
isUserInRipe = computedAsync(() => this.profile()?.personId?.id ? this.#getIsRipe(this.profile()?.personId?.id: false, { initialValue: false }); // Signal<boolean>
canEditPerson = computed(() => this.#canEditPerson(this.isUserInRipe(), this.userArnes()?.role, this.userArnes()?.source)); // Signal<boolean>


#getIsRipe(personId: number) : Observable<boolean>{
    return this.#personService
      .hasUserRipe(personId)
      .pipe(
        showError<boolean>(() => {
          this.#uiService.showErrorFlashMessage("Napaka pri preverjanju RIPE statusa");
          return EMPTY;
        })
      );
  }

#canEditPerson = (isRipe: boolean, role: Role, source: Source): boolean => {
....
}
```

- this code in ver 2.0.0 

```
s not assignable to parameter of type 'boolean'.
  Type 'Observable<boolean>' is not assignable to type 'boolean'.

   canEditPerson = computed(() => this.#canEditPerson(this.isUserInRipe(), this.userArnes()?.role, this.userArnes()?.source));
```

- even if I change `canEditPerson = computedAsync(() => this.#canEditPerson(this.isUserInRipe(), this.userArnes()?.role, this.userArnes()?.source));`  the same error

![compuredAsyncpng](https://github.com/nartc/ngxtension-platform/assets/69830/01f7f17d-2d19-4df7-929d-f546c290ea95)

**Comment by sysmat** [comment]
ok, my mistake ; in guard I return false, so type is then union, so I need of(false)

`this.profile()?.personId?.id ? this.#getIsRipe(this.profile()?.personId?.id: of(false)`

**Comment by sysmat** [comment]
- If I return null in guard then it also works, what is the best practice?

`isUserInRipe = computedAsync(() => this.profile()?.personId?.id ? this.#getIsRipe(this.profile()?.personId?.id) : null, { initialValue: false });`

**Comment by eneajaho** [comment]
Hello @sysmat 
In version 2.0.0 **computedAsync** has better type checking and is surfacing the errors you had before (that couldn't be captured by the types)

More info in these PRs: 

https://github.com/nartc/ngxtension-platform/pull/257
https://github.com/nartc/ngxtension-platform/pull/255

**Comment by sysmat** [comment]
@eneajaho thx, and what is best practice, to return `null` or `of(false)`

**Comment by eneajaho** [comment]
Both are valid. 

I'd go with false.

**Comment by sysmat** [comment]
@eneajaho thx
