### ISSUE TITLE
createNotifier TS2307: Cannot find module 'ngxtension/create-notifier' or its corresponding type declarations.

### ISSUE THREAD

**Issue by sysmat** [nartc/ngxtension-platform#285]
- "ngxtension": "2.0.0"
- doc: https://ngxtension.netlify.app/utilities/signals/create-notifier/

there is doc but in lib, in which version is this supported?

**Comment by joshuamorony** [comment]
Yeah the docs update automatically when merged into main I think - @nartc can we cut a new release?

**Comment by sysmat** [comment]
any progress?

**Comment by joshuamorony** [comment]
@sysmat 2.1.0 is out now

**Comment by sysmat** [comment]
@joshuamorony thx, it works
