### ISSUE TITLE
[docs] [signalSlice] Add docs on actionEffects

### ISSUE THREAD

**Issue by Pilpin** [nartc/ngxtension-platform#292]
Hello, would it be possible to add documentation and examples on actionEffects ?
Thx a lot for these libs, they are amazing.

**Comment by joshuamorony** [comment]
I've left `actionEffects` undocumented as it is still somewhat experimental, however it's probably a good idea to add some docs anyway perhaps with a warning - I'll get something up soon

**Comment by joshuamorony** [comment]
@Pilpin the docs won't be updated until the PR is merged, but you can just look at the files changed in the PR now if you like
