### ISSUE TITLE
[Docs]: Maintain sidenav scroll state

### ISSUE THREAD

**Issue by tanishqmanuja** [nartc/ngxtension-platform#302]
### Problem Statement 
Suppose I am looking for stuff related to signals. I click Signals > signalSlice (Browser Navigation happens). Then the scroll state of sidenav is gone and i have to re scroll to signals section.

Isn't a major issue, but yeah definitely a UX improvement is possible.

The solution could be as simple as scrolling the selected href element into view after each page transition

**Comment by Dafnik** [comment]
This seems to also be an upstream issue. https://github.com/withastro/starlight/discussions/971
