### ISSUE TITLE
computedAsync - missing Signal equality functions

### ISSUE THREAD

**Issue by dmpost** [nartc/ngxtension-platform#317]
We need [equality func](https://angular.io/api/core/ValueEqualityFn) for computedAsync.

Which can be added to [signal](https://angular.io/api/core/signal)() or [computed](https://angular.io/api/core/computed)():

`data = signal(['test'], {equal: _.isEqual});`

or 

`data = computed(() => {...}, {equal: () => false});`

I use computedAsync a lot, 
and often add Date.now() to the result to make it unique, otherwise the same values are ignored.

**Comment by kkachniarz220** [comment]
But there is `equal` fn 
![image](https://github.com/nartc/ngxtension-platform/assets/50884231/581b6d61-d676-4d5f-8661-fb0aaf9089ba)

**Comment by eneajaho** [comment]
Hello @dmpost 
As @kkachniarz220 has said, equal already is part of computedAsync. Closing this issue as it's already working.

**Comment by dmpost** [comment]
Oh, 
yes indeed, didn't found it in docs.

Great 
thnx
