### ISSUE TITLE
[feat] add trackById and trackByProp directives

### ISSUE THREAD

**Issue by dmorosinotto** [nartc/ngxtension-platform#33]
Don't you mind if I'll add this function?
https://gist.github.com/dmorosinotto/8deeb5b2db6c6dfcb9a927268ef85745
They are two standalone directives to help/easy handle trackBy in *ngFor , the original code is inspired by this [article](https://medium.com/ngconf/make-trackby-easy-to-use-a3dd5f1f733b)

**Comment by nartc** [comment]
Go for it!

**Comment by dmorosinotto** [comment]
@nartc I'll start to implement this, now that I have some "practice" with the other PR 
I only have 1 question: what kind of test can I create for something like trackBy??
I'm not a text expert, but can't think of something "useful" to test if the directive trackById and trackByOther really works, because they will set an input for the ngForTrackBy input and alter the behavior of the renderer, but how I can test it? any suggestion?
