### ISSUE TITLE
ngxtension:convert-di-to-inject - Error: Unknown argument: path

### ISSUE THREAD

**Issue by paradox37** [nartc/ngxtension-platform#331]
Hello,

I want to report a bug with `ng g ngxtension:convert-di-to-inject --path=<path-to-ts-file>`.

When I run the command, I get the message: `Error: Unknown argument: path`.

To ensure there is no mistake on my side, I tried `ng g ngxtension:convert-signal-inputs --path=<path-to-ts-file>` and it works fine.

**Comment by eneajaho** [comment]
Hello @paradox37 
The feature is still in [PR](https://github.com/nartc/ngxtension-platform/pull/326) and it's not merged yet. Will be merged this week I believe.

**Comment by paradox37** [comment]
@eneajaho Okay. I found it in the documentation so I assumed it was already implemented.

**Comment by eneajaho** [comment]
> @eneajaho Okay. I found it in the documentation so I assumed it was already implemented.

Yeah true. Sorry for the confusion, this feature should be merged this week.
