### ISSUE TITLE
[feat] slight different takeUntilDestroy pattern

### ISSUE THREAD

**Issue by dmorosinotto** [nartc/ngxtension-platform#36]
I know you have just created the [injectDestory](https://github.com/nartc/ngxtension-platform/blob/main/libs/ngxtension/inject-destroy/src/inject-destroy.ts) fn but in my project I used to have a base.component that implements the "takeUntilDestory" pattern to help safe unsubscribe: https://gist.github.com/dmorosinotto/efae3315e1339597fca0921b7c944385

And recently changed it with this helper fn:   [injectTakeUntilDestory](https://github.com/dmorosinotto/XE_Modernize_Angular/blob/master/src/app/shell/base.component.ts#L5-L14)

Do you think that it may be added or an accept a "modified" version of your `injectDestory` fn?

**Comment by nartc** [comment]
How about exposing a base `DestroyableComponent` with `takeUntilDestroy` from `ngxtension/inject-destroy` entry point?

**Comment by dmorosinotto** [comment]
I rarely use the destory$ subject in my component, for me it is just an "implementation detail" to have the takeUntilDestory operator, if you take a look of my initial base.component and the new `injectTakeUntilDestory` fn at the end my final scope is to add a *"custom operator"* scoped to the component to easily use the .pipe(...., takeUntilDestory() )   without any parameter o "Subject signal" but maybe I'm missing something and you really need the destroy$ in some cases

**Comment by nartc** [comment]
I assumed that you'd want something to replace `BaseComponent` so that you wouldn't have to change a lot of downstream code. 

I suggested that we add a `DestroyableComponent` to `ngxtension/inject-destroy` entry point (i.e: `import { DestroyableComponent } from 'ngxtension/inject-destroy'`)

Or `BaseComponent` can be rewritten as follow:

```ts
import { Directive } from "@angular/core";
import { takeUntil } from 'rxjs';
import { injectDestroy } from 'ngxtension/inject-destroy';

@Directive() // Needed only for Angular v9+ strict mode that enforce decorator to enable Component inheritance
export abstract class BaseComponent {
  private destroy$ = injectDestroy();
  protected takeUntilDestroy = () => {
    return takeUntil(this.destroy$);
  }
}
```

One thing you can also improve is to make `injectDestroy()` creates the underlying `destroy$` Subject lazily.

**Comment by dmorosinotto** [comment]
I mostly refactor my code using the `injectTakeUntilDestory` 
I keep my BaseComponent just for _"historical reason"_ (aka not break/refactor all my components), but this is my project concern, maybe for a utils lib the pattern more useful is to expose the `injectTakeUntilDestory` helper fn, not a DestoybleComponent that may be a constraint dependency , If some want a BaseComponent (as I have done) can easily build and name it as they wish using the "behavior" using the injectTakeUntilDestory helper fn.
I'm NOT suggestion to remove your injectDestory fn, just eventually add the injectTakeUntilDestory

**Comment by nartc** [comment]
I see. If that's the case, I don't think `injectTakeUntilDestroy` provides any apparent value in addition to `injectDestroy`

```ts
export class SomeComponent {
    destroy$ = injectDestroy();

    ngOnInit() {
        interval(1000).pipe(takeUntil(this.destroy$));
    }
}

// versus
export class SomeComponent {
    takeUntilDestroy = injectTakeUntilDestroy();

    ngOnInit() {
        interval(1000).pipe(this.takeUntilDestroy());
    }
}
```

**Comment by majies** [comment]
Not sure if I'm 100% following this correctly, but does all this get fixed by angular takeUntilDestory (currently dev preview) from rxjs-interop which will emit on current destory injection context or you can pass in your own reference

https://angular.io/api/core/rxjs-interop/takeUntilDestroyed

**Comment by nartc** [comment]
I'm pretty sure @eneajaho has an explanation for `injectDestroy`.

**Comment by eneajaho** [comment]
yeah just left a comment here: https://twitter.com/Enea_Jahollari/status/1702346249855197491

**Comment by dmorosinotto** [comment]
@nartc the value added from my implementation is that using it you don't need 2 import to make it work, because you don't need to import { takeUntil } from "rxjs"  , just some keystroke saved ;-)

@eneajaho  responded in the Twitter/X thread

@majies You are totally right, looked inside the "official" Angular implementation, at the end is quite similar to mine, I use a Subject, the create a lightway Observable that next/complete onDetroy, so the Angular code is even better than mine, and I can totally see a way to refactor my BaseComponent class using it.

So if all you agree, I can close this Issue because it can be solved without implementing a new method in ngxtension (less code to manintain for everyone), and just keeeping the actual `injectDestory` implementation as-is for those who prefer having a "Subject signaling" when the component (or service) is destroied ;-)

Sorry to the noise, and thanks for all you feedback and comments

**Comment by eneajaho** [comment]
@dmorosinotto 
I wouldn't call it noise, it's constructive discussion (so thank you for all the feedback) that other devs can read and learn more about different ways of doing things and using what they like. 

**injectDestroy** has existed for some time before coming in ngxtension. 

Here are two more tweets about it that may be interesting to other people: 

 - https://twitter.com/Enea_Jahollari/status/1691571381215936751
 - https://twitter.com/Enea_Jahollari/status/1630665586245242881
 
 I'm closing this issue, but the **discussion can continue**!

**Comment by dmorosinotto** [comment]
Yes I know and use the "destory$" pattern from years, and even mine `BaseComponent` in many personal project, but with the new **inject** FOMO from NG14+ I slight change it, to finally arrive where we are now with the implementation of the takeUntilDestoryed done by the Angular guys, finally solving this problem for all of us without need of our "poor dev" custom solutions 😜 

Thanks to all of you for the constructive discussion!
I'll go to dedicate some times to other issues I've opened, but right now I need a little ☕  and rest because today was a full-intense day 😉

**Comment by nartc** [comment]
@dmorosinotto I think we're looking at things from a different point of view here. I don't think we should always tie a `destroy$` subject to just `takeUntil`. There are different use-cases where a notification of when a component's destroyed would be beneficial. For example an `AlertComponent` that can be closed by 3 different ways:
- The user clicks on "X" explicitly
- After 5 seconds
- The parent component is destroyed

```ts
merge(closeClick$, timer(5000), destroy$)
    .pipe(take(1))
    .subscribe(() => {
        // some logic to close Alert
    });
```

**Comment by dmorosinotto** [comment]
Yes @nartc you are right, I use the "keystroke saving" just to say don't have to use a double dependency and hide it in an "internal detail" of the ngxtension implementation, and totally agree that `injectDestroy` maybe useful in other use-cases different to the takeUntil, what I may be suggest is that I'll need to use it just to takeUntil probably I'll go to the "official" Angular implementation just to have an all-in-one "behavior" but this is just my personal preference 😉
