### ISSUE TITLE
RFC add initialValue to computedFrom fn

### ISSUE THREAD

**Issue by dmorosinotto** [nartc/ngxtension-platform#37]
I follow all your works (article/twit) about `computedForm` and various iterations, and then tried to add something to it: the optional `initialValue` changing a bit of the internal implementation, to not discover the initial values from Obs, but simply relay to the Angular toObservable option using "requireSync" [here](https://gist.github.com/dmorosinotto/0d3d27423e2e8e417ec8f22cc05c1905#file-computedfrom-ts) you can find the code, hope this can be considered or discussed...  

I propose this because I agree that you can easily solve the problem of initial "sync value" for observables using startWith, but I was concerned of cases where the user forgot this and have failing code, adding simple optional to set the initialValue of the resulting Output type maybe and easy task, and at the end if the user just used the startWith in the observable the initial combineLatest have all ready values to compute the first emit, and calling the toObservable with requiredSync will NOT error, but if you have some "later Observable" where you forgot to use startWith and you DON'T pass initialValue it will generate the runtime error, so the user know how to fix the problem (maybe)

**Comment by nartc** [comment]
cc @eneajaho I'll let you discuss this one

**Comment by eneajaho** [comment]
Hello @dmorosinotto 
In fact the current implementation doesn't throw an error, but gives that observable a null initialValue. 
We thought on that (throwing an error or just returning null), and returning null imo was the right choice, because this way the user will be able to see their value will return null. Throwing an error is too intrusive imo. 

[This example from the docs explain that part carefully. 
](https://ngxtension.netlify.app/utilities/computed-from/#3-combine-multiple-signals-and-observables)
```ts
const page$ = new Subject<number>(); // Subject doesn't have an initial value
const filters$ = new BehaviorSubject({ name: 'John' });
const combined = computedFrom([page$, filters$]);

console.log(combined()); // [null, { name: 'John' }] // we don't want console.log to throw an error here
```

I hope I was clear, and if not, please let me know what exactly do you think, by also providing some code we can look at. 

I highly appreciate this discussions.

**Comment by dmorosinotto** [comment]
@eneajaho take a look at this [stackbliz repo](https://stackblitz.com/edit/stackblitz-starters-9snor4?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts&title=Angular%20Starter)  
this is my concern:

```typescript
const ret = combined(); //INFERRED TYPE [ number, [name:string} ]
    console.log(ret); //OK IT "JUST" WORKS HERE I LOG [null, {name: 'John'}]
    //HERE COME THE REAL PROBLEM...
    const OPS =
      ret[0].toExponential(); /* TYPESCIPT WILL NOT PREVENT OR "SIGNAL" ME ANYTHING!
```
Sorry for pun, but here i have a runtime error because the **REAL** ret[0] type is `number|null`  <-- and just for this particular runtime case! I don't know it you can "strict-type" this use-case correctly, so you are just "delaying" the Runtime Error to other place, maybe more "problematic" to handle/find because TS don't help here to correct it.

This is why I prefer to have a _RuntimeError_ in `computedFrom` if I pass a "late obs$" without natural "sync value" and forgot to pass an optional `initialValue` in mine implementation  (plus passing it, let user choose a different output initialValue maybe not null but something else let's say `[42, {name:''}]` ) this is my 2 cents..

What do you think?

**Comment by dmorosinotto** [comment]
Hi @eneajaho, I know you are busy man to keep up with Angular news and update, but please can you evaluate my request and give a response to this issue? 
Changing the computedForm to safe handle the initialValue, may even resolve the issue about the "spurious" initial sync emit of null or of the array of values that you documented... 
I'll be very happy to discuss the possible upgrade directions here, and then take the time to open a PR and  implement it, please give me some feedback before I'll invest my time to do something that is not needed/wanted 🙏

**Comment by eneajaho** [comment]
Hello @dmorosinotto 
I'm thinking of having sth like: 

```ts
let data = computedFrom(
  [this.page, this.filters$],
  pipe(([page, filters]) => this.service.get(page, filters)),
  { initialValue: [], /* injector: this.injector injector is optional */ }
)
```

What do you think?

**Comment by dmorosinotto** [comment]
Hi @eneajaho thanks for you response, YES I'm totally in with this idea, and I think that the 3rd argument can be of  type [ToSignalOptions](https://angular.io/api/core/rxjs-interop/ToSignalOptions) so we can use it to customize the internal call toSignal with all options not just initialValue or injector what do you think?
