### ISSUE TITLE
[RFC] minimal signal store

### ISSUE THREAD

**Issue by nartc** [nartc/ngxtension-platform#38]
Hi folks,

I'm presenting `signalStore` as a minimal Signal Store to ease the pain of managing state with Signal.

## Target

I know that most folks would probably use some State Management libraries: `ngrx`, `rx-angular`, `state-adapt` etc... with Angular. However, `signalStore()` would make sense for folks who build Angular **libraries** where we do not want to depend on a full-fledged state management library.

## API

```ts
type SignalStore<State extends object> = {
  select<
    Key1 extends keyof State,
    Key2 extends keyof State[Key1],
    Key3 extends keyof State[Key1][Key2],
    Key4 extends keyof State[Key1][Key2][Key3],
  >(
    key1: Key1,
    key2: Key2,
    key3: Key3,
    key4: Key4,
    options?: CreateComputedOptions<State[Key1][Key2][Key3][Key4]>,
  ): Signal<State[Key1][Key2][Key3][Key4]>;
  select<
    Key1 extends keyof State,
    Key2 extends keyof State[Key1],
    Key3 extends keyof State[Key1][Key2],
  >(
    key1: Key1,
    key2: Key2,
    key3: Key3,
    options?: CreateComputedOptions<State[Key1][Key2][Key3]>,
  ): Signal<State[Key1][Key2][Key3]>;
  select<Key1 extends keyof State, Key2 extends keyof State[Key1]>(
    key1: Key1,
    key2: Key2,
    options?: CreateComputedOptions<State[Key1][Key2]>,
  ): Signal<State[Key1][Key2]>;
  select<Key extends keyof State>(
    key: Key,
    options?: CreateComputedOptions<State[Key]>,
  ): Signal<State[Key]>;
  select(options?: CreateComputedOptions<State>): Signal<State>;

  get<
    Key1 extends keyof State,
    Key2 extends keyof State[Key1],
    Key3 extends keyof State[Key1][Key2],
    Key4 extends keyof State[Key1][Key2][Key3],
  >(
    key1: Key1,
    key2: Key2,
    key3: Key3,
    key4: Key4,
  ): State[Key1][Key2][Key3][Key4];
  get<
    Key1 extends keyof State,
    Key2 extends keyof State[Key1],
    Key3 extends keyof State[Key1][Key2],
  >(
    key1: Key1,
    key2: Key2,
    key3: Key3,
  ): State[Key1][Key2][Key3];
  get<Key1 extends keyof State, Key2 extends keyof State[Key1]>(
    key1: Key1,
    key2: Key2,
  ): State[Key1][Key2];
  get<Key extends keyof State>(key: Key): State[Key];
  get(): State;

  set(state: Partial<State> | ((previous: State) => Partial<State>)): void;
  patch(state: Partial<State>): void;

  state: Signal<State>;
};
```

- `select()` accepts keys and nested keys (up to 4 levels). `select()` caches and returns the computed `Signal` for the keys.
- `get()` behaves similarly to `select()` but it returns the value imperatively instead of `Signal`
- `set()` behaves similarly to `WriteableSignal#update` but the update is wrapped with `untracked()` so it is safe to use inside of `effect()` and other places.
- `patch()` is a little unique. It behaves like `set()`, except the `previous` state is applied **AFTER** the incoming state. This ensures incoming `undefined` data doesn't override the previous data. 
- `state` is similar to `select()` without arguments.
- internal `_snapshot`: this is a non-configurable, non-enumerable getter on the `store` object. Useful for debugging current state at the time the getter is read.

`signalStore()` accepts an `initialState` either as a `Partial<State>` or `(storeApi: Pick<SignalStore<State>, 'get' | 'set' | 'patch'>) => Partial<State>`
- the function version is particularly helpful when your initial state needs some computation / logic you want to encapsulate in the `signalStore()` function.

https://gist.github.com/nartc/b34a6000d2f2e2c552842d7281ca356e

### `untracked` or not

`signalStore` current implementation wraps update calls in `untracked`. This is because, in Angular Three's Renderer, things invoke Signal updates during Render, which causes issues with "Update Signal during render". I personally would like to keep the behavior, but we can definitely make it configurable via `signalStore()` signature.

### Usage

```ts
const store = signalStore({ 
  foo: 'default foo', 
  bar: { baz: 'nested', quz: 123 } 
});

// select lazily creates Signal and caches the created computed
const foo = store.select('foo'); // Signal<string>

// select nested property
const baz = store.select('bar', 'baz'); // Signal<string>

// select also accepts CreateComputedOptions
const bar = store.select('bar', { equal: Object.is }); // Signal<{ baz: string, quz: number }>

// read value imperatively at this point
const fooValue = store.get('foo'); // string;

// same nested property syntax
const bazValue = store.get('bar', 'baz');

// state is the readonly Signal
const state = store.state; // Signal<{ foo: string, bar: { baz: string, quz: number } }>

// want to control the computed Signal of the whole store, use select()
const customState = store.select({ equal: equalityFn });

// update state
store.set({ foo: 'updated foo' }); // accepts Partial state
store.set(prev => ({ bar: { ...prev.bar, quz: prev.bar.quz + 1 } }); // accepts update fn that can return Partial state

// (rare usage, Angular Three uses this API) patch state
store.patch({ foo: 'updated foo' }); // state.get('foo') === 'updated foo'
store.patch({ foo: undefined }); // state.get('foo') === 'updated foo'; using patch WILL NOT update the state if the value is "undefined". This API helps with cases where some Inputs have default values and those default values should NOT be overridden by "undefined" values

store.set({ foo: undefined }); // state.get('foo') === undefined; using set WILL ALWAYS update the state

// (rare usage, Angular Three uses this API) functional store creation
signalStore<Counter>(({ set, get, select }) => {
  /* some internal custom logic to the store creation phase */

  const count = select('count'); // Signal<number>

  return {
    count: 1,
    incrementCount: 0,
    decrementCount: 0,
    increment: () => set(prev => ({ count: prev.count + 1, incrementCount: prev.incrementCount + 1 })),
    decrement: () => set(prev => ({ count: prev.count - 1, decrementCount: prev.decrementCount + 1 })),
    double: computed(() => count() * 2)
  }
})
```
Check out one example from [Angular Three](https://github.com/angular-threejs/angular-three/blob/platform/libs/soba/misc/src/example/example.ts)

**Comment by dmorosinotto** [comment]
Maybe it's a bit late, and I need to go sleep, but I don't get the motivation for `untraked` in setter/patcher and getter? 
Q: Doing so you loose the building of **dependency graph** from the internal signal and the external consumer= (aka effect/computed that try to use/read the state)

**Comment by nartc** [comment]
@dmorosinotto you don't actually lose the dep graph

**Comment by eneajaho** [comment]
Would be great if we could see how it's used @nartc

**Comment by nartc** [comment]
@eneajaho usage added

**Comment by tomer953** [comment]
just sharing my opinion, no offense at all - ngrx/component-store already has this exact api (kind of) and it being well maintain and popular  

including signal store could cause a lot more issues and maintenance imo, feels too big and complex comparing to some small rxjs and signals common utils.
 I read your note about Library authors, not sure how strong this argu, you start small then adapt for some rare use-cases and bugs then you finish in the same size as ngrx.

**Comment by nartc** [comment]
I use ComponentStore everyday. But they just don't have the set of features that I need. I.e: untracked update invokes

**Comment by tomer953** [comment]
> I use ComponentStore everyday. But they just don't have the set of features that I need. I.e: untracked update invokes

Ok i trust you’re know what you’re doing :)
If you have time to explain what you’re missing in the ngrx/component-store ill glad to learn. I’m using it too and not sure what the untracked mode means… 
besides that, in ngrx we can do evertyhing you mentioned (i think so):
state can be set lazily, passing custom equality function, select, patch, updater, etc…

**Comment by nartc** [comment]
1. `untracked` update means to run the update methods (i.e: `update()`, `mutate()`, `set()`) in `untracked(() => {})`. Due to the nature of [Angular Three](https://angular-threejs.netlify.app) being a custom Angular Renderer, there are cases where a Signal update during render and throws Signal errors. Wrapping a custom store impl's update methods in `untracked()` solves this issue. I'm not 100% sure of what the downside is, but I haven't ran into a difference between `untracked()` vs no `untracked()`. 
2. `ngrx/component-store` doesn't have a `patch` API like I mention above where an `undefined` update would **NOT** override an existing non-undefined state. The use-case is something like this:

```ts
@Component({})
export class GrandChild {
    private inputs = signalStore<GrandChildInputs>({ foo: 'default foo' });
    
    @Input() set foo(foo: string) {
        // incoming input might have "undefined" accidentally
        this.inputs.patch({ foo });
    }
}

@Component({
    template: `
        <!-- this might or might not send "undefined"  -->
        <grand-child [foo]="someObjectThatMightContainFoo.foo" />
    `
})
export class Child {
    someObjectThatMightContainFoo = {};
}
```

Both cases are from Angular Three's usages so it might not (and hard to wrap your head around) apply to others. However, a standalone `signalStore` might still benefit consumers of `ngxtension` if we make the `untracked` API configurable. 

On the other hand, it might not beneficial at all if folks default to solutions like `ngrx/component-store` and the likes.

**Comment by dmorosinotto** [comment]
If you develop the signalStore I will prefer to have it configurable for both the "special case" `untracked` becouse I'm not sure of possible other unwanted side-effect... and even for `ignoring undefined` becouse is possible that someone want to explicit store this value on one prop and maybe doesn't expect to have no way to see their code work: `my_store.patch({ my_optional_prop: undefined });` - it's a RARE case but why not?

Obviously you can configure the options with the defaults that you prefer (something like)
```ts
const defaultStoreOptions = {
   untrackedUpdate: true,
   ignoreUndefined: true
}
```
This is my 2cents, but eager to 👀 the real implementation

**Comment by eneajaho** [comment]
When can this land?

**Comment by nartc** [comment]
@eneajaho tomorrow if you want LMAO

**Comment by nartc** [comment]
I had a chance to take a closer look at NgRX `signalState` by Marko and I think it's a better addition to `ngxtension` (with some minor adjustments) than my `signalStore`. For folks that don't use `ngrx` in their application, I think a standalone `signalState` would be beneficial. Thoughts?

**Comment by nartc** [comment]
Based on my conversation with Marko, we'd like to keep the implementation to NgRx itself. The API will be exposed via `@ngrx/signals` which is a completely standalone package.                                           Consumers should be using that instead.
