### ISSUE TITLE
rxjs Helper

### ISSUE THREAD

**Issue by tomalaforge** [nartc/ngxtension-platform#41]
-`filterArray` and `mapArray` to filter and map on array value => avoid doing the `obs$.pipe(map(arr => arr.filter(...)))`

- `filterNullUndefined` to filter null and undefined values on observable steams

**Comment by dmorosinotto** [comment]
Can I suggest a different naming for _filterNullUndefined_ --> `filterNil`

**Comment by tomalaforge** [comment]
@eneajaho @nartc what do you think?

**Comment by nartc** [comment]
PRs are welcome!

**Comment by tomer953** [comment]
Someone close ? :)
