### ISSUE TITLE
[chore] Request for a little Nx guide to CONTRIBUTION.md

### ISSUE THREAD

**Issue by dmorosinotto** [nartc/ngxtension-platform#46]
Hi can you please add a "little guide" to CONTRIBUTION.md to correctly setup a new "secondary-entrypoint" to the lib, for help the dev workflow for the _"non-**NX**-addicted"_ devs like me 😜  

I know, I must learn to use it (and maybe this is the right time for me) but some help is really appreciated
Thanks

**Comment by nartc** [comment]
CONTRIBUTING guide has been updated. Please check it out [secondary entry point](https://github.com/nartc/ngxtension-platform/blob/main/CONTRIBUTING.md#secondary-entry-point)

**Comment by dmorosinotto** [comment]
Thanks 🙏
