### ISSUE TITLE
Docs: sort utils by name

### ISSUE THREAD

**Issue by tomer953** [nartc/ngxtension-platform#60]
Since the repo is going to grow,
I think its a good idea to arrange the utils list.

Ie from:

- [resize](https://ngxtension.netlify.app/utilities/resize)
- [create-injection-token](https://ngxtension.netlify.app/utilities/create-injection-token)
- [assert-injector](https://ngxtension.netlify.app/utilities/assert-injector)
- [repeat](https://ngxtension.netlify.app/utilities/repeat)
- [computed-from](https://ngxtension.netlify.app/utilities/computed-from)
- [inject-destroy](https://ngxtension.netlify.app/utilities/inject-destroy)
- [connect](https://ngxtension.netlify.app/utilities/connect)
- [create-effect](https://ngxtension.netlify.app/utilities/create-effect)
- [if-validator](https://ngxtension.netlify.app/utilities/if-validator)
- [navigation-end](https://ngxtension.netlify.app/utilities/navigation-end)

To:
- [assert-injector](https://ngxtension.netlify.app/utilities/assert-injector)
- [computed-from](https://ngxtension.netlify.app/utilities/computed-from)
- [connect](https://ngxtension.netlify.app/utilities/connect)
- [create-effect](https://ngxtension.netlify.app/utilities/create-effect)
- [create-injection-token](https://ngxtension.netlify.app/utilities/create-injection-token)
- [if-validator](https://ngxtension.netlify.app/utilities/if-validator)
- [inject-destroy](https://ngxtension.netlify.app/utilities/inject-destroy)
- [navigation-end](https://ngxtension.netlify.app/utilities/navigation-end)
- [repeat](https://ngxtension.netlify.app/utilities/repeat)
- [resize](https://ngxtension.netlify.app/utilities/resize)

(Thanks GPT for the sorting)

Another approach is to categorised them (directives, operators, utils)

**Comment by nartc** [comment]
I 100% agree. Would you like to submit a PR?

**Comment by tomer953** [comment]
yeah NP
I will
