### ISSUE TITLE
[RFC] Additional Intl API suggestion

### ISSUE THREAD

**Issue by wanoo21** [nartc/ngxtension-platform#72]
I'm not sure if it's the case, but **it might be a good idea to add some additional Intl APIs**, such as  [ListFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat), [RelativeTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat) and others.

I built a collection of [Intl pipes](https://github.com/wanoo21/ngx-intl-helper/blob/main/helpers/README.md) a while ago, to support a few of them, and I could add some here if that is the case 🙂.

**Comment by nartc** [comment]
Would love to have these in the library. Can you submit a PR?

**Comment by wanoo21** [comment]
Sure, all of them?

**Comment by nartc** [comment]
Since I'm not sure what you have in mind so it's entirely up to you. We can iterate over the PR process
