### ISSUE TITLE
computedFrom type guard when using filter

### ISSUE THREAD

**Issue by tomer953** [nartc/ngxtension-platform#76]
Expected:
computedFrom operator should allow type narrowing
Small example using filterNil()  to reproduce:

  ```ts
n = signal<number | undefined | null>(3);

    // filter with typeguard is working
    x$ = of(this.n()).pipe(
      filter((x): x is number => Boolean(x)),
      map((x) => (x as number) + 1)
    );
   
    // filterNil has typeguard already
    y$ = of(this.n()).pipe(
      filterNil(),
      map((x) => x + 1)
    );
  
    // but with computedFrom it failes to narrow
    z$ = computedFrom(
      [this.n],
      pipe(
        filterNil(),
        map(([x]) => x + 1) // x is possibly null or undefined
      )
    );
```

z$ should act like y$
I can’t find why this happens, @nartc  might help here

_Originally posted by @tomer953 in https://github.com/nartc/ngxtension-platform/issues/73#issuecomment-1728715539_

**Comment by tomalaforge** [comment]
`filterNil'  only works for simple values, not array, and computedFrom is passing an array of element to your operator function

We would need a `filterArrayNil` or something similar

**Comment by tomer953** [comment]
oh i see. i thought the computedFrom flatten the array behind the scenes. 
so actually its not broken. my bad
