### ISSUE TITLE
[docs] categorise utils

### ISSUE THREAD

**Issue by eneajaho** [nartc/ngxtension-platform#79]
<img width="285" alt="CleanShot 2023-09-23 at 11 18 22@2x" src="https://github.com/nartc/ngxtension-platform/assets/25394362/038a2a63-b8e2-4359-82f9-cd95475b70f5">

We need to categorise utils for easier navigation as the list is becoming big!

**Comment by tomer953** [comment]
I Agree (and suggested it before)

lets suggeste categories? 

- RxJS Operators
- Directives
- Pipes
- Signals
- Inject utils (?)
- Misc.

**Comment by tomer953** [comment]
updated with some examples, help with the rest plz

**Comment by wanoo21** [comment]
I think it would be lovely to structure the body content, not just the menu. 

To have a standard, like this:

1. Introduction - What is it? Why do we need it? In two words - The problem.
2. Usage - Importing & examples with descriptions.
3. Configurations - Examples and descriptions, including default options if any.
4. Error Handling and/or Fallbacks.

This is just an idea, is just what I have in mind now.

Also, the body should contain 1 or 2 backlinks if it's the case, especially for newbies that will explain why you should use this over that. 🤷🏻‍♂️

**Comment by e-oz** [comment]
I would add the "State Management" category.

**Comment by LcsGa** [comment]
Instead of directives, pipes, etc. categories, and as sometimes we could have different types in one feature + as the name state the lib is tought to be an extension of angular 👉 shouldn't we try to put them in the same packages as angular (eg: core, core/rxjs-interrop, common, etc.)?

**Comment by tomer953** [comment]
Can you provide example with the current utils? not sure how well its fit

**Comment by LcsGa** [comment]
For example:
- `computedFrom` or `connect` are used for rxjs interoperability 👉 they could be placed into `core/rxjs-interop`
- `trackBy` is a tool of `NgFor` which is in `common` 👉  thus we could add `TrackById / TrackByProp` into `common`
- the `AsyncPipe` is also part of `common` 👉 we could add `CallPipe / AsyncPipe` into `common` too
- `assertInInjectionContext` is witin `core` 👉 we could add `assertInjection` within `core`
- rxjs operators, on the contrary, could be placed within a new package as I personnaly don't think that it should be placed within the interop package (I may be wrong)
- etc.
