### ISSUE TITLE
[RFC] imitate the angular packages structure

### ISSUE THREAD

**Issue by LcsGa** [nartc/ngxtension-platform#82]
As the name of the project suggests it, it is intended to be an extension of angular.

Thus, since everything implemented is related to the existing angular subentries, and as the project evolves pretty quickly, wouldn't it be easier to find wher IS what if we imitate the angular architecture with thé core, common, etc. packages?

**Comment by nartc** [comment]
We sure can in terms of directory structure of the library itself. As far as import path goes (i.e: `ngxtension/***`), we cannot do much there because nesting any further will require additional npm packages which we don't want. Let's discuss the directory structure in #83 and #79
