### ISSUE TITLE
[RFC] createInjectionToken with support of multi: true

### ISSUE THREAD

**Issue by wanoo21** [nartc/ngxtension-platform#95]
I started to rewrite some of my libraries and added ngxtension.

I'm using [createInjectionToken](https://ngxtension.netlify.app/utilities/injectors/create-injection-token/) quite often and I've noticed I can't create a multi-token - `multi: true`.

I checked the source code and I don't see to be a way to mark it as multiple.

<img width="409" alt="image" src="https://github.com/nartc/ngxtension-platform/assets/6537167/4a75ea0b-9fd1-4965-9d77-4ad4b1528355">

Maybe there's a workaround I can't find out?

**Comment by nartc** [comment]
That's right. I'll take a look at this.

**Comment by nartc** [comment]
@wanoo21 added a fix but I'd like to point this out.

https://github.com/nartc/ngxtension-platform/pull/98/files#diff-28c9dd83d9c535288ff51d6470317daabbcffec42e587608c98810c47c71cddcR111

You can see here that `provideFn()` is called twice in the `providers` array. The first call is to make sure the provided factory is run. If not, then the value returned will only include the 2nd call `provideFn(2)`.

**Comment by wanoo21** [comment]
Cool, thank you, nice addition!
I'd like to provide some other suggestions. 

How about adding support for the **Generic type and marking the factory as optional**?

So basically this:
`export const TOKEN = new InjectionToken<MyType>();`

becomes:
`export const [injectFn, provideFn] = createInjectionToken<MyType>();`

There's a problem though, I can't make it `multi` without providing the factory 🤷🏻‍♂️

Also, considering the code above, would this work?
`provideFn(() => {
  const foo = inject(FOO);
  if (foo) return 'something'
  return 'something else'
})`

Instead of a simple value, to provide a factory!

This is how I manage it now:
<img width="453" alt="image" src="https://github.com/nartc/ngxtension-platform/assets/6537167/9351f61c-9874-416f-83ed-4007201da3bf">

**Comment by nartc** [comment]
@wanoo21 open a new issue on that please
