### ISSUE TITLE
[RFC] createInjectionToken generic type and optional factory

### ISSUE THREAD

**Issue by wanoo21** [nartc/ngxtension-platform#99]
I'd like to provide some other suggestions.

How about adding support for the **Generic type and marking the factory as optional**?

So basically this:
`export const TOKEN = new InjectionToken<MyType>();`

becomes:
`export const [injectFn, provideFn] = createInjectionToken<MyType>();`

There's a problem though, I can't make it `multi` without providing the factory 🤷🏻‍♂️

Also, considering the code above, would this work?
`provideFn(() => {
  const foo = inject(FOO);
  if (foo) return 'something'
  return 'something else'
})`

Instead of a simple value, to provide a factory!

This is how I manage it now:
<img width="453" alt="image" src="https://github.com/nartc/ngxtension-platform/assets/6537167/9351f61c-9874-416f-83ed-4007201da3bf">

**Comment by nartc** [comment]
1. For the first case where you need optional factory and `multi`, you can use the following workaround for now
```ts
// note the "!" non-null assertion.
export const [injectFn, provideFn] = createInjectionToken<MyType>(() => null!, { multi: true });
```

2. `provideFn()` accepting a factory is tricky. What's the main difference between the following?

```ts
export const [injectFn, provideFn] = createInjectionToken(() => {
    const foo = inject(FOO, { optional: true });
    if (foo) return 'something'
    return 'something else';
}, { multi: true });
provideFn();

// versus
provideFn(() => { const foo = inject(FOO); if (foo) return 'something' return 'something else' })
```

**Comment by wanoo21** [comment]
Okay, `not-null null` sounds cool :) But it's okay for this approach!

So what I'm trying to achieve is to have a multi-token that contains some objects. Sometimes, I need to `inject` other tokens to create the object.

For example:
```ts
export const [injectBlocks, provideBlock] = createInjectionToken((): MyBlock[] => [], { multi: true });
```

Adding needed blocks:
```ts
// image.block.ts
provideBlock(() => {
 const locale = inject(LOCALE);
 return {
   type: 'image',
   align: locale === 'en-US' ? 'left' : 'right' // just an example
 }
})

// text.block.ts
provideBlock(() => {
 const direction = inject(Directionality);
 return {
   type: 'text',
   textAlign: direction.value === 'ltr' ? 'left' : 'right'
 }
})
```

Somewhere in the main component:
```ts
readonly blocks = injectBlocks(); // -> [{type: 'image' ...}, {type: 'text', ...}]
```

Is there a workaround for this now?

**Comment by nartc** [comment]
hm....there's not a workaround now unfortunately. I'll add support for passing factories into `provideFn`
